#ifndef SIZES_H
#define SIZES_H

#define KILOBYTE 1000
#define MEGABYTE (KILOBYTE * 1000)

#define STACK_SIZE (MEGABYTE * 1)
#define DATA_SEGMENT_SIZE (MEGABYTE * 1)
#define LOCALS_SIZE (MEGABYTE * 1)

#endif